### ISSUE TITLE
Fix-Script: Aktenzeichen

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.maintenance#48]
Wir brauchen ein Fix-Script, das die Aktenzeichen auf einem System neu rechnen/generieren kann. Die folgende Problematik soll dabei gelöst werden:

- Es kann sein, dass die Mappings (child_mapping/prefix_mapping) eines `ReferenceNumberPrefixAdpater` nicht persistent sind. Diese sollen in persistente Objekte konvertiert werden.
- `Reference Number`s für alle **Dossiers** sollen komplett neu erstellt werden (unter der Annahme, dass die alten Nummern unbrauchbar sind weil z.B. teilweise doppelt vergeben). Eine mögliche sinnvolle Nummerierung wäre nach `get_position_in_parent`.
- `Reference Number`s für die **Ordnungspositionen** müssen erhalten bleiben
- Catalog soll für alle Dossiers/Ordnungspositionen aktualisiert werden (Metadaten/Index `reference`)

Es gibt schon eine view, die mögliche Probleme aufzeigt: https://github.com/4teamwork/opengever.maintenance/blob/master/opengever/maintenance/browser/refnum_selfcheck.py

**Comment by jone** [comment]
See also: https://github.com/4teamwork/opengever.core/issues/1521, https://github.com/4teamwork/opengever.core/issues/1561
